### ISSUE TITLE
Expand Tolerance options

### ISSUE THREAD

**Issue by GerardMoscardo** [chaostoolkit/chaostoolkit-lib#85]
According to documentation i can only get responses from an http method as string.
But tolerance using [int, int] only allows int and fails on the steady state validation.

Example:

    {
        "type": "probe",
        "name": "CCCCC",
        "tolerance":: [1,10000],
        "provider": {
          "type": "http",
          "url": "http://localhost:3000/metrics/query",
          "method": "POST",
          "arguments": {
            "query": any service returning a string",
            "datasource": 161
          }
   }

**Comment by Lawouach** [comment]
Hey,

Indeed, the basic tolerance with a sequence like this one cannot handle the returned body from a HTTP probe. The reason is that such probe returns an object (a mapping) such as:

```
{
    "status": 200,
    "headers": {...},
    "body": "..."
}
```

Here, the default tolerance range will look at the status, not the actual body.

To support this, we actually need a more complex new tolerance type, following the principles of the jsonpath and regex tolerances.

```
"tolerance": {
    "type": "range",
    "target": "body",
    "range": {
        "min": 10,
        "max": 1000
    }
}
```

When the body is a string, this can be reduced to:

```
"tolerance": {
    "type": "range",
    "target": "body",
    "range": ["good", "better", "best"]
}
```

assuming:

```
{
    "status": 200,
    "headers": {...},
    "body": "bad"
}
```

Please have a look https://github.com/chaostoolkit/chaostoolkit-lib/pull/84 and see if it helps?

**Comment by Lawouach** [comment]
While discussing with @GerardMoscardo, I wondered if it wasn't confusing to have ` "range": ["good", "better", "best"]`? Indeed, this could be achieved with a simple regex already. Maybe the range, should really stick to numerical values between low and high?

**Comment by GerardMoscardo** [comment]
Hello, IMO, as u said, range should be only used for numerical values.

**Comment by Lawouach** [comment]
I agree.

In that case, should we use a shorter syntax:


```
"tolerance": {
    "type": "range",
    "target": "body",
    "range": [-10, 10]
}```

Basically, low/high and the value must between those boundaries.

**Comment by GerardMoscardo** [comment]
This looks perfect, also shares syntax with the other probes already existing:

> A sequence tolerance with lower and upper bounds:
> 
> "tolerance": [4, 9]

Thanks!

**Comment by Lawouach** [comment]
Exactly!

I'll update the PR asap.

**Comment by Lawouach** [comment]
Documented in https://github.com/chaostoolkit/chaostoolkit-documentation/commit/c8a58f756d8e6dc2af28fa89a49894475b0716a8
