### ISSUE TITLE
Ensure steady state hypothesis is met after Rollback

### ISSUE THREAD

**Issue by dimzak** [chaostoolkit/chaostoolkit-lib#94]
Hi,

I've been testing `chaostoolkit` and stumbled upon below scenario:

During a successful experiment run, `rollback` was unsuccessful, changing the system and basically bringing the app down, yet experiment was successful:

#### Rollback configuration in experiment:
`app-must-be-healthy` is a probe ref of `steady-state-hypothesis`
```

    "rollbacks": [
        {
            "type": "action",
            "name": "restart-app",
            "provider": {
                "type": "process",
                ....
                ....
          },
            "pauses": {
                "after": 5
            }
        },
        {
            "ref": "app-must-be-healthy"
        }
    ]

```
---
#### Experiment logs:
```
chaostoolkit_1  | [2019-04-04 13:48:13 INFO] Steady state hypothesis is met!
chaostoolkit_1  | [2019-04-04 13:48:13 INFO] Let's rollback...
chaostoolkit_1  | [2019-04-04 13:48:13 INFO] Rollback: restart-app
chaostoolkit_1  | [2019-04-04 13:48:13 INFO] Action: restart-app
chaostoolkit_1  | [2019-04-04 13:48:13 INFO] Pausing after activity for 5s...
chaostoolkit_1  | [2019-04-04 13:48:18 INFO] Rollback: None
chaostoolkit_1  | [2019-04-04 13:48:18 INFO] Probe: app-must-be-healthy
chaostoolkit_1  | [2019-04-04 13:48:18 ERROR]   => failed: failed to connect to http://nginx:80/health: HTTPConnectionPool(host='nginx', port=80): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f91218d54e0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
chaostoolkit_1  | [2019-04-04 13:48:18 INFO] Experiment ended with status: completed
```
Would it make sense to re-evaluate `steady-state-hypothesis` and experiment result after rollback?

P.S. I hope I opened this issue correctly here and not in https://github.com/chaostoolkit  :)

**Comment by Lawouach** [comment]
Hi,

First of all, you caught a minor bug as a side note of your issue here. In theory, rollbacks can only see actions, not probes. This would be caught by the validation pass but because you used a ref, it missed it I opened #96 for this.

It's a good question. But I would argue that, if you are experimenting the impact of a rollback procedure (that you have for instance), it should be its own dedicated experiment.

Rollbacks in experiments are not promises :) We are very careful about that because the action you carried initially may have set your systems in a very different state. Rollbacks work well in a test because you tend to control everything, in a chaos experiment, they merely undo if they can.  

I'd say you discovered a potential weakness unbeknownst to you :)
